# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'manual_image.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        self.i = 0
        Form.setObjectName("Form")
        Form.resize(680, 495)
        Form.setStyleSheet("background-color: rgb(2, 31, 108);\n"
"")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(40, 410, 81, 26))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(540, 410, 81, 26))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(160, 400, 351, 71))
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(60, 30, 561, 351))
        self.label.setStyleSheet("image: url(manual_0);")
        self.label.setText("")
        self.label.setObjectName("label")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

        self.left_next()
        self.right_next()


    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton.setText(_translate("Form", "<---"))
        self.pushButton_2.setText(_translate("Form", "--->"))
# import test_rc
#     i  = 0
    def left_next(self):
        a = 'left'
        self.pushButton.clicked.connect(lambda :self.move(a))
    def right_next(self):
        a = 'right'
        self.pushButton_2.clicked.connect(lambda :self.move(a))

    def move(self, side):
        if side == 'left':
            if self.i == 0:
                print('yes_0')
                pass
            elif self.i > 0:
                print('yes_1')
                self.i -= 1
                a = f'manual_{self.i}'

                self.label.setStyleSheet(f"image: url({a});")
        elif side == 'right':
            if self.i >= 4:
                print('no_0')
                pass
            elif self.i < 4:
                print('no_1')
                self.i += 1
                a = f'manual_{self.i}'
                self.label.setStyleSheet(f"image: url({a});")



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
