# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'manual_image.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        self.i = 0
        Form.setObjectName("Form")
        Form.resize(680, 495)
        Form.setStyleSheet("background-color: rgb(2, 31, 108);\n"
                           "")
        self.bt_left = QtWidgets.QPushButton(Form)
        self.bt_left.setGeometry(QtCore.QRect(40, 410, 81, 26))
        self.bt_left.setStyleSheet("background-color: rgb(1, 44, 161);")
        self.bt_left.setObjectName("bt_left")
        self.bt_right = QtWidgets.QPushButton(Form)
        self.bt_right.setGeometry(QtCore.QRect(540, 410, 81, 26))
        self.bt_right.setStyleSheet("background-color: rgb(1, 44, 161);")
        self.bt_right.setObjectName("bt_right")
        self.text_setings = QtWidgets.QLabel(Form)
        self.text_setings.setGeometry(QtCore.QRect(160, 380, 351, 71))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(False)
        self.text_setings.setFont(font)
        self.text_setings.setStyleSheet("color: rgb(255, 255, 255);")
        self.text_setings.setText("")
        self.text_setings.setObjectName("text_setings")
        self.image_setings = QtWidgets.QLabel(Form)
        self.image_setings.setGeometry(QtCore.QRect(60, 0, 541, 371))
        self.image_setings.setText("")
        self.image_setings.setPixmap(QtGui.QPixmap("manual_0.png"))
        self.image_setings.setScaledContents(True)
        self.image_setings.setObjectName("Image_setings")
        self.bt_exit = QtWidgets.QPushButton(Form)
        self.bt_exit.setGeometry(QtCore.QRect(270, 460, 141, 31))
        self.bt_exit.setStyleSheet("background-color: rgb(1, 44, 161);")
        self.bt_exit.setObjectName("bt_exit")
        self.text_setings.setText('нажмите на кнопку старт для начала игры')

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

        self.left_next()
        self.right_next()

        self.settings_text_info = {
            '0': 'нажмите на кнопку старт для начала игры',
            '1': 'система автоматически случайным образом задасть значения кучек кмней.',
            '2': "в полня how 'many stones' и 'what bunch' вставьет значения той кучки\n"
                 " из которой вы хотите вычесть камне и вставьте значени того\n"
                 " колличества камней которо вы хотитте отнять и выбранной кучи\n"
                 "нажмите move",
            '3': 'ход передается другому игроку который должен выполнить теже\n'
                 'действия',
            '4': 'действия выполняются пока колличество камней в каждой куче\n не бдует равна нулю',
            '5': 'выигрывает тот игрок который забрал последний камень\n их всех 3 кучек'
        }

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.bt_left.setText(_translate("Form", "<---"))
        self.bt_right.setText(_translate("Form", "--->"))
        self.bt_exit.setText(_translate("Form", "exit"))

    def left_next(self):
        a = 'left'
        self.bt_left.clicked.connect(lambda: self.move(a))

    def right_next(self):
        a = 'right'
        self.bt_right.clicked.connect(lambda: self.move(a))

    def move(self, side):
        if side == 'left':
            if self.i == 0:
                print('yes_0')
                self.text_setings.setText(self.settings_text_info[str(self.i)])
                pass
            elif self.i > 0:
                print('yes_1')
                self.i -= 1
                a = f'../../../Applications/Python project/python_Evy37/pyqt5/manual/manual_{self.i}.png'
                self.text_setings.setText(self.settings_text_info[str(self.i)])
                self.image_setings.setPixmap(QtGui.QPixmap(f"{a}"))
        elif side == 'right':
            if self.i >= 5:
                self.text_setings.setText(self.settings_text_info[str(self.i)])
                print('no_0')
                pass
            elif self.i < 5:
                print('no_1')
                self.i += 1
                a = f'../../../Applications/Python project/python_Evy37/pyqt5/manual/manual_{self.i}.png'
                self.text_setings.setText(self.settings_text_info[str(self.i)])
                self.image_setings.setPixmap(QtGui.QPixmap(f"{a}"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    st_im_mn = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(st_im_mn)
    st_im_mn.show()
    sys.exit(app.exec_())
