# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DGU_sistems.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DGU_sistem(object):
    def setupUi(self, DGU_sistem):
        DGU_sistem.setObjectName("DGU_sistem")
        DGU_sistem.resize(600, 489)
        self.kurs = QtWidgets.QLabel(DGU_sistem)
        self.kurs.setGeometry(QtCore.QRect(50, 100, 60, 16))
        self.kurs.setObjectName("kurs")
        self.profil = QtWidgets.QLabel(DGU_sistem)
        self.profil.setGeometry(QtCore.QRect(50, 170, 71, 16))
        self.profil.setObjectName("profil")
        self.dd_orders = QtWidgets.QLabel(DGU_sistem)
        self.dd_orders.setGeometry(QtCore.QRect(50, 310, 181, 16))
        self.dd_orders.setObjectName("dd_orders")
        self.name = QtWidgets.QLabel(DGU_sistem)
        self.name.setGeometry(QtCore.QRect(50, 30, 60, 16))
        self.name.setObjectName("name")
        self.type_social = QtWidgets.QLabel(DGU_sistem)
        self.type_social.setGeometry(QtCore.QRect(50, 240, 201, 16))
        self.type_social.setObjectName("type_social")
        self.input_kurs = QtWidgets.QLineEdit(DGU_sistem)
        self.input_kurs.setGeometry(QtCore.QRect(50, 120, 500, 22))
        self.input_kurs.setObjectName("input_kurs")
        self.input_profil = QtWidgets.QLineEdit(DGU_sistem)
        self.input_profil.setGeometry(QtCore.QRect(50, 190, 500, 22))
        self.input_profil.setText("")
        self.input_profil.setObjectName("input_profil")
        self.input_type_social = QtWidgets.QLineEdit(DGU_sistem)
        self.input_type_social.setGeometry(QtCore.QRect(50, 260, 500, 22))
        self.input_type_social.setObjectName("input_type_social")
        self.input_dd_orders = QtWidgets.QLineEdit(DGU_sistem)
        self.input_dd_orders.setGeometry(QtCore.QRect(50, 330, 500, 22))
        self.input_dd_orders.setObjectName("input_dd_orders")
        self.input_name = QtWidgets.QLineEdit(DGU_sistem)
        self.input_name.setGeometry(QtCore.QRect(50, 50, 500, 22))
        self.input_name.setObjectName("input_name")

        self.retranslateUi(DGU_sistem)
        QtCore.QMetaObject.connectSlotsByName(DGU_sistem)

    def retranslateUi(self, DGU_sistem):
        _translate = QtCore.QCoreApplication.translate
        DGU_sistem.setWindowTitle(_translate("DGU_sistem", "Form"))
        self.kurs.setText(_translate("DGU_sistem", "Курс"))
        self.profil.setText(_translate("DGU_sistem", "Профиль"))
        self.dd_orders.setText(_translate("DGU_sistem", "Дата назначанеия и срок"))
        self.name.setText(_translate("DGU_sistem", "ФИО"))
        self.type_social.setText(_translate("DGU_sistem", "Вид социальной стипендии"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DGU_sistem = QtWidgets.QWidget()
    ui = Ui_DGU_sistem()
    ui.setupUi(DGU_sistem)
    DGU_sistem.show()
    sys.exit(app.exec_())
