# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt


class Ui_TETT(object):
    def setupUi(self, TETT):
        self.box = [1,2,3]
        TETT.setObjectName("TETT")
        TETT.resize(514, 443)
        self.chBox = QtWidgets.QCheckBox(TETT)
        self.chBox.setGeometry(QtCore.QRect(130, 160, 85, 21))
        self.chBox.setObjectName("chBox")
        self.checkBox_2 = QtWidgets.QCheckBox(TETT)
        self.checkBox_2.setGeometry(QtCore.QRect(130, 230, 85, 21))
        self.checkBox_2.setObjectName("checkBox_2")

        self.retranslateUi(TETT)
        QtCore.QMetaObject.connectSlotsByName(TETT)


        self.ttt()

    def retranslateUi(self, TETT):
        _translate = QtCore.QCoreApplication.translate
        TETT.setWindowTitle(_translate("TETT", "TETTt"))
        self.chBox.setText(_translate("TETT", "Box1"))
        self.checkBox_2.setText(_translate("TETT", "Box2"))


    def ttt(self):
        self.chBox.stateChanged.connect(self.tttt )


    def tttt(self, state):
        if state == Qt.Checked:
            self.box[0] = 33
            print(self.box)
        else:
            print('no')

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TETT = QtWidgets.QWidget()
    ui = Ui_TETT()
    ui.setupUi(TETT)
    TETT.show()
    sys.exit(app.exec_())
