# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'game_menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Game_Menu(object):
    def setupUi(self, Game_Menu):
        Game_Menu.setObjectName("Game_Menu")
        Game_Menu.resize(518, 460)
        font = QtGui.QFont()
        font.setPointSize(30)
        Game_Menu.setFont(font)
        Game_Menu.setStyleSheet("background-color: rgb(2, 31, 108);\n"
                                "background-color: rgb(2, 31, 108);\n"
                                "")
        self.centralwidget = QtWidgets.QWidget(Game_Menu)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setEnabled(True)
        self.pushButton.setGeometry(QtCore.QRect(220, 210, 81, 26))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("color: rgb(200, 186, 255);\n"
                                      "background-color: rgb(2, 31, 108);\n"
                                      "")
        self.pushButton.setCheckable(False)
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(100, 20, 321, 41))
        font = QtGui.QFont()
        font.setPointSize(50)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(200, 186, 255);\n"
                                      "background-color: rgb(2, 31, 108);\n"
                                      "")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(230, 110, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(200, 186, 255);\n"
                                      "background-color: rgb(2, 31, 108);\n"
                                      "")
        self.label_2.setObjectName("label_2")
        Game_Menu.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Game_Menu)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 518, 21))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        Game_Menu.setMenuBar(self.menubar)
        self.action = QtWidgets.QAction(Game_Menu)
        self.action.setObjectName("action")
        self.action_2 = QtWidgets.QAction(Game_Menu)
        self.action_2.setObjectName("action_2")
        self.menu.addAction(self.action_2)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(Game_Menu)
        QtCore.QMetaObject.connectSlotsByName(Game_Menu)

    def retranslateUi(self, Game_Menu):
        _translate = QtCore.QCoreApplication.translate
        Game_Menu.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "NIMS"))
        self.label.setText(_translate("MainWindow", "Главное меню"))
        self.label_2.setText(_translate("MainWindow", "игры "))
        self.menu.setTitle(_translate("MainWindow", "функции"))
        self.action.setText(_translate("MainWindow", "главное меню"))
        self.action_2.setText(_translate("MainWindow", "главное меню"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Game_Menu = QtWidgets.QMainWindow()
    ui = Ui_Game_Menu()
    ui.setupUi(Game_Menu)
    Game_Menu.show()
    sys.exit(app.exec_())
