# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'nim.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_nim(object):
    def setupUi(self, nim):
        nim.setObjectName("nim")
        nim.resize(579, 423)
        nim.setStyleSheet("background-color: rgb(2, 31, 108);\n"
"")
        self.bt_start = QtWidgets.QPushButton(nim)
        self.bt_start.setGeometry(QtCore.QRect(70, 50, 81, 26))
        self.bt_start.setStyleSheet("color: rgb(200, 186, 255);\n"
"background-color: rgb(51, 53, 140);\n"
"\n"
"")
        self.bt_start.setObjectName("bt_start")
        self.bt_reset = QtWidgets.QPushButton(nim)
        self.bt_reset.setGeometry(QtCore.QRect(190, 50, 81, 26))
        self.bt_reset.setStyleSheet("color: rgb(200, 186, 255);\n"
"background-color: rgb(51, 53, 140);")
        self.bt_reset.setObjectName("bt_reset")
        self.bt_end = QtWidgets.QPushButton(nim)
        self.bt_end.setGeometry(QtCore.QRect(310, 50, 81, 26))
        self.bt_end.setStyleSheet("color: rgb(200, 186, 255);\n"
"background-color: rgb(51, 53, 140);")
        self.bt_end.setObjectName("bt_end")
        self.label = QtWidgets.QLabel(nim)
        self.label.setGeometry(QtCore.QRect(150, 250, 111, 20))
        self.label.setStyleSheet("color: rgb(200, 186, 255);\n"
"background-color: rgb(2, 31, 108);\n"
"")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(nim)
        self.label_2.setGeometry(QtCore.QRect(340, 250, 100, 20))
        self.label_2.setStyleSheet("color: rgb(200, 186, 255);\n"
"background-color: rgb(2, 31, 108);\n"
"")
        self.label_2.setObjectName("label_2")
        self.chose_bunch = QtWidgets.QLineEdit(nim)
        self.chose_bunch.setGeometry(QtCore.QRect(150, 270, 111, 20))
        self.chose_bunch.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(51, 53, 140);")
        self.chose_bunch.setObjectName("chose_bunch")
        self.input_nummber_bunch = QtWidgets.QLineEdit(nim)
        self.input_nummber_bunch.setGeometry(QtCore.QRect(340, 270, 100, 20))
        self.input_nummber_bunch.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(51, 53, 140);")
        self.input_nummber_bunch.setObjectName("input_nummber_bunch")
        self.bt_move = QtWidgets.QPushButton(nim)
        self.bt_move.setGeometry(QtCore.QRect(260, 370, 81, 26))
        self.bt_move.setStyleSheet("color: rgb(200, 186, 255);\n"
"background-color: rgb(51, 53, 140);")
        self.bt_move.setObjectName("bt_move")
        self.label_3 = QtWidgets.QLabel(nim)
        self.label_3.setGeometry(QtCore.QRect(250, 320, 101, 16))
        self.label_3.setMinimumSize(QtCore.QSize(0, 0))
        self.label_3.setSizeIncrement(QtCore.QSize(0, 0))
        self.label_3.setBaseSize(QtCore.QSize(0, 0))
        self.label_3.setStyleSheet("color: rgb(200, 186, 255);\n"
"background-color: rgb(2, 31, 108);\n"
"")
        self.label_3.setObjectName("label_3")
        self.info_banch_1 = QtWidgets.QLabel(nim)
        self.info_banch_1.setGeometry(QtCore.QRect(120, 200, 60, 16))
        self.info_banch_1.setStyleSheet("color: rgb(200, 186, 255);\n"
"background-color: rgb(2, 31, 108);\n"
"")
        self.info_banch_1.setObjectName("info_banch_1")
        self.info_banch_2 = QtWidgets.QLabel(nim)
        self.info_banch_2.setGeometry(QtCore.QRect(260, 200, 60, 16))
        self.info_banch_2.setStyleSheet("color: rgb(200, 186, 255);\n"
"background-color: rgb(2, 31, 108);\n"
"")
        self.info_banch_2.setObjectName("info_banch_2")
        self.info_banch_3 = QtWidgets.QLabel(nim)
        self.info_banch_3.setGeometry(QtCore.QRect(400, 200, 60, 16))
        self.info_banch_3.setStyleSheet("color: rgb(200, 186, 255);\n"
"background-color: rgb(2, 31, 108);\n"
"")
        self.info_banch_3.setObjectName("info_banch_3")
        self.img_bunch_1 = QtWidgets.QLabel(nim)
        self.img_bunch_1.setGeometry(QtCore.QRect(110, 140, 61, 60))
        self.img_bunch_1.setText("")
        self.img_bunch_1.setPixmap(QtGui.QPixmap("page_bunch.png"))
        self.img_bunch_1.setObjectName("img_bunch_1")
        self.img_bunch_2 = QtWidgets.QLabel(nim)
        self.img_bunch_2.setGeometry(QtCore.QRect(250, 140, 61, 60))
        self.img_bunch_2.setText("")
        self.img_bunch_2.setPixmap(QtGui.QPixmap("page_bunch.png"))
        self.img_bunch_2.setObjectName("img_bunch_2")
        self.img_bunch_3 = QtWidgets.QLabel(nim)
        self.img_bunch_3.setGeometry(QtCore.QRect(390, 140, 61, 60))
        self.img_bunch_3.setText("")
        self.img_bunch_3.setPixmap(QtGui.QPixmap("page_bunch.png"))
        self.img_bunch_3.setObjectName("img_bunch_3")
        self.instruction = QtWidgets.QPushButton(nim)
        self.instruction.setGeometry(QtCore.QRect(440, 50, 81, 26))
        self.instruction.setStyleSheet("color: rgb(200, 186, 255);\n"
"background-color: rgb(51, 53, 140);")
        self.instruction.setObjectName("instruction")

        self.retranslateUi(nim)
        QtCore.QMetaObject.connectSlotsByName(nim)

    def retranslateUi(self, nim):
        _translate = QtCore.QCoreApplication.translate
        nim.setWindowTitle(_translate("nim", "Form"))
        self.bt_start.setText(_translate("nim", "Start"))
        self.bt_reset.setText(_translate("nim", "Reset"))
        self.bt_end.setText(_translate("nim", "End"))
        self.label_2.setText(_translate("nim", "what bunch"))
        self.bt_move.setText(_translate("nim", "move"))
        self.label_3.setText(_translate("nim", "Ход игрока №1"))
        self.info_banch_1.setText(_translate("nim", "Bunch 1"))
        self.info_banch_2.setText(_translate("nim", "Bunch 2"))
        self.info_banch_3.setText(_translate("nim", "Bunch 3"))
        self.instruction.setText(_translate("nim", "instruction"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    nim = QtWidgets.QWidget()
    ui = Ui_nim()
    ui.setupUi(nim)
    nim.show()
    sys.exit(app.exec_())
