# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_test(object):
    def setupUi(self, test):
        test.setObjectName("test")
        test.resize(692, 385)
        test.setStyleSheet("background-color: rgb(8, 11, 28);")
        self.clickButton = QtWidgets.QPushButton(test)
        self.clickButton.setGeometry(QtCore.QRect(310, 160, 81, 26))
        self.clickButton.setStyleSheet("background-color: rgb(79, 255, 62);\n"
"color: rgb(255, 0, 7);")
        self.clickButton.setObjectName("pushButton")

        self.retranslateUi(test)
        QtCore.QMetaObject.connectSlotsByName(test)

    def retranslateUi(self, test):
        _translate = QtCore.QCoreApplication.translate
        test.setWindowTitle(_translate("test", "Form"))
        self.clickButton.setText(_translate("test", "Button"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    test = QtWidgets.QWidget()
    ui = Ui_test()
    ui.setupUi(test)
    test.show()
    sys.exit(app.exec_())
